# For more info on HTTP files go to https://aka.ms/vs/httpfile


GET https://localhost:7070/Product
Accept: application/json;charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcHJpbWFyeXNpZCI6IjEiLCJleHAiOjE3MTAzMjM0MjUsImlzcyI6IlNob3BPbmxpbmVJc3N1ZXIiLCJhdWQiOiJTaG9wT25saW5lQXVkaWVuY2UifQ.-EEQS7KUZPgW51Aar9eynBU9yoY_ZmatuTTqqXRmqp8

